### ISSUE TITLE
New revision of the mini

### ISSUE THREAD

**Issue by Julusian** [ryankurte/rust-streamdeck#22]
Elgato have snuck out a new revision of the mini with product id 0x0090

The only difference is in the get_feature_request call for retrieving the serial number, which you do not appear to be doing, so I expect you can treat it exactly the same as the older revision of the mini.

I do not need this myself, simply sharing the knowledge from [javascript land](https://github.com/julusian/node-elgato-stream-deck) for someone who does

**Comment by ryankurte** [comment]
hey thanks for the heads up! (also wow i didn't know about WebHID, looks like fun ^_^)
