### ISSUE TITLE
Revised mini's keys are 1-indexed rather than 0-indexed

### ISSUE THREAD

**Issue by keirlawson** [ryankurte/rust-streamdeck#30]
Running the following on my streamdeck mini (revised version) sets the top left button's colour

```sh
cargo run -- --pid 0090 set-colour 1 --b 100 --g 100 --r 100
```

However, running the equivalent command against the Mk2 sets the 2nd from left button:

```sh
cargo run -- --pid 0080 set-colour 1 --b 100 --g 100 --r 100
```

**Comment by ryankurte** [comment]
oh fun! guess we should probably detect and patch that so the API stays consistent.

**Comment by keirlawson** [comment]
Ok, I guess `translate_key_index` is the place to do that, just wondering if its worth introducing a new `button_offset` field on `Kind` or whether we should just directly check for the revised mini, thoughts?

**Comment by ryankurte** [comment]
don't think it matters a whole lot, but, i'd lean towards the latter because it's sorta nice having all the _quirks_ described in the `Kind` object
